### PR TITLE
feat: migrated to `@xhayper/discord-rpc`

### LINKED ISSUE #56: cannot read property 'write' of null
im using m1 mac

this is my init.vim right now
Screen Shot 2021-09-02 at 10 04 57 PM

and the error is
```[coc.nvim] Error on activate extension coc-discord-rpc: Cannot read property 'write' of null```

### LINKED ISSUE #59: Cannot read properties of null reading "write"
Been coding on nvim and I installed this Plugin until encountered this error

Screenshot_20211119_165633

### PR DESCRIPTION
**Pull request by xhayper**
This is a successor to #63

This should fix #59 and fix #56, if it doesn't lmk.

### CODE REVIEW

**Comment by xhayper** [comment]
Confirmed to work with snap version of Discord.

**Comment by xhayper** [comment]
@leonardssh please review these changes.

**Comment by KarlWithK** [comment]
My only suggestion is to please remove the yarn.lock from this commit.

**Comment by leonardssh** [comment]
@KarlWithK we actually need yarn.lock file to be able to cache the yarn install step on CI/CD workflows.

**Comment by KarlWithK** [comment]
Ah I didn't know that! That sounds cool!

**Comment by SirCharlieMars** [comment]
Is there blockers from this pr being merged?

**Pull request closed without merging**
